server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiple-intances
          uri: https://github.com/Anddres98/Microservicio
          search-paths: config-data
  application:
    name: config-service


